FROM python:3.9-slim

#Install dependencies required for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY object_detection_service.py .

CMD ["uvicorn", "object_detection_service:app", "--host", "0.0.0.0", "--port", "8000"]

